name: flutter_widget_wrapper
description: This is a flutter widget measurement widget and notify current size
version: 0.0.1
repository: https://github.com/Mohiuddin655-PRO/flutter_widget_wrapper.git

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
